basePath: /
definitions:
  dto.Album:
    properties:
      artist:
        type: string
      id:
        type: string
      price:
        type: number
      title:
        type: string
    type: object
  dto.HTTPError:
    properties:
      message:
        example: something went wrong, bad request, not_found, unathorized ...
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /posts:
    get:
      consumes:
      - application/json
      description: ListPosts responds with the list of all albums as JSON.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Album'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.HTTPError'
      summary: ListPosts responds with the list of all albums as JSON.
      tags:
      - albums
swagger: "2.0"
